import type { ServerFormData } from "@/components/server-creation-wizard"

type ServerTemplate = {
  id: string
  name: string
  description: string
  gameType: string
  tags: string[]
  popular?: boolean
  new?: boolean
  config: ServerFormData
}

// Real server templates with proper configurations
export const serverTemplates: ServerTemplate[] = [
  // Minecraft Templates
  {
    id: "minecraft-vanilla",
    name: "Minecraft Vanilla",
    description: "Standard Minecraft server with default settings",
    gameType: "minecraft",
    tags: ["vanilla", "survival", "beginner-friendly"],
    popular: true,
    config: {
      name: "Minecraft Vanilla Server",
      gameType: "minecraft",
      description: "A standard Minecraft vanilla server",
      version: "1.20.4",
      port: 25565,
      maxPlayers: 20,
      serverProperties: {
        difficulty: "normal",
        gamemode: "survival",
        pvp: "true",
        "spawn-protection": "16",
        "max-tick-time": "60000",
        "view-distance": "10",
        "server-port": "25565",
        "enable-command-block": "false",
        "allow-nether": "true",
        "enforce-whitelist": "false",
      },
      cpu: 2,
      memory: 4,
      storage: 10,
      enableMods: false,
      mods: [],
      startupCommands: "java -Xmx4G -Xms1G -jar server.jar nogui",
      backupEnabled: true,
      backupSchedule: "0 0 * * *",
      autoRestart: true,
      restartSchedule: "0 4 * * *",
    },
  },
  {
    id: "minecraft-modded",
    name: "Minecraft Modded",
    description: "Minecraft server with Forge and essential mods pre-installed",
    gameType: "minecraft",
    tags: ["modded", "forge", "enhanced"],
    config: {
      name: "Minecraft Modded Server",
      gameType: "minecraft",
      description: "A Minecraft server with Forge and essential mods",
      version: "1.19.2",
      port: 25565,
      maxPlayers: 15,
      serverProperties: {
        difficulty: "normal",
        gamemode: "survival",
        pvp: "true",
        "spawn-protection": "16",
        "allow-flight": "true",
        "view-distance": "8",
        "server-port": "25565",
        "enable-command-block": "true",
        "allow-nether": "true",
        "enforce-whitelist": "false",
      },
      cpu: 4,
      memory: 8,
      storage: 20,
      enableMods: true,
      mods: [
        "forge-1.19.2-43.2.0",
        "jei-1.19.2-11.5.0.297",
        "waystones-forge-1.19-11.4.0",
        "BiomesOPlenty-1.19.2-17.1.1.162",
        "create-1.19.2-0.5.1.c",
      ],
      startupCommands: "java -Xmx8G -Xms2G -jar forge-1.19.2-43.2.0.jar nogui",
      backupEnabled: true,
      backupSchedule: "0 */12 * * *",
      autoRestart: true,
      restartSchedule: "0 4 * * *",
    },
  },

  // CS:GO Templates
  {
    id: "csgo-competitive",
    name: "CS:GO Competitive",
    description: "CS:GO server configured for competitive 5v5 matches",
    gameType: "csgo",
    tags: ["competitive", "5v5", "esports"],
    popular: true,
    config: {
      name: "CS:GO Competitive Server",
      gameType: "csgo",
      description: "A CS:GO server configured for competitive 5v5 matches",
      version: "latest",
      port: 27015,
      maxPlayers: 10,
      serverProperties: {
        sv_cheats: "0",
        mp_autoteambalance: "0",
        mp_limitteams: "0",
        mp_freezetime: "15",
        mp_maxrounds: "30",
        mp_roundtime: "1.92",
        sv_pausable: "1",
        sv_pure: "1",
        sv_lan: "0",
        sv_allow_votes: "0",
        mp_match_can_clinch: "1",
        mp_overtime_enable: "1",
        mp_overtime_maxrounds: "6",
        mp_halftime: "1",
      },
      cpu: 4,
      memory: 8,
      storage: 20,
      enableMods: false,
      mods: [],
      startupCommands:
        "./srcds_run -game csgo -console -usercon +game_type 0 +game_mode 1 +mapgroup mg_active +map de_dust2 -tickrate 128 -port 27015 +sv_setsteamaccount YOURGSLTTOKEN -net_port_try 1",
      backupEnabled: true,
      backupSchedule: "0 0 * * *",
      autoRestart: true,
      restartSchedule: "0 4 * * *",
    },
  },
  {
    id: "csgo-casual",
    name: "CS:GO Casual",
    description: "CS:GO server for casual gameplay with relaxed settings",
    gameType: "csgo",
    tags: ["casual", "beginner-friendly"],
    config: {
      name: "CS:GO Casual Server",
      gameType: "csgo",
      description: "A CS:GO server for casual gameplay",
      version: "latest",
      port: 27015,
      maxPlayers: 20,
      serverProperties: {
        sv_cheats: "0",
        mp_autoteambalance: "1",
        mp_limitteams: "2",
        mp_freezetime: "6",
        mp_maxrounds: "15",
        mp_roundtime: "3",
        sv_pausable: "0",
        sv_pure: "1",
        sv_lan: "0",
        sv_allow_votes: "1",
        mp_halftime: "1",
      },
      cpu: 2,
      memory: 4,
      storage: 15,
      enableMods: false,
      mods: [],
      startupCommands:
        "./srcds_run -game csgo -console -usercon +game_type 0 +game_mode 0 +mapgroup mg_allclassic +map de_dust2 -tickrate 64 -port 27015 +sv_setsteamaccount YOURGSLTTOKEN -net_port_try 1",
      backupEnabled: true,
      backupSchedule: "0 0 * * *",
      autoRestart: true,
      restartSchedule: "0 4 * * *",
    },
  },

  // Valheim Templates
  {
    id: "valheim-standard",
    name: "Valheim Standard",
    description: "Standard Valheim server for cooperative survival gameplay",
    gameType: "valheim",
    tags: ["survival", "cooperative", "pve"],
    config: {
      name: "Valheim Standard Server",
      gameType: "valheim",
      description: "A standard Valheim server for cooperative survival gameplay",
      version: "latest",
      port: 2456,
      maxPlayers: 10,
      serverProperties: {
        password: "valheim",
        public: "1",
        savedir: "./saves",
        backups: "true",
        backupshort: "true",
        backuplong: "true",
        instanceid: "Valheim",
        savedir: "./saves",
      },
      cpu: 2,
      memory: 6,
      storage: 10,
      enableMods: false,
      mods: [],
      startupCommands:
        './valheim_server.x86_64 -nographics -batchmode -name "Valheim World" -port 2456 -world "Dedicated" -password "valheim" -public 1',
      backupEnabled: true,
      backupSchedule: "0 */12 * * *",
      autoRestart: true,
      restartSchedule: "0 4 * * *",
    },
  },

  // Terraria Templates
  {
    id: "terraria-standard",
    name: "Terraria Standard",
    description: "Standard Terraria server for adventure and building",
    gameType: "terraria",
    tags: ["adventure", "building", "multiplayer"],
    config: {
      name: "Terraria Standard Server",
      gameType: "terraria",
      description: "A standard Terraria server for adventure and building",
      version: "1.4.4.9",
      port: 7777,
      maxPlayers: 8,
      serverProperties: {
        difficulty: "1",
        autocreate: "2",
        worldname: "TerrariaWorld",
        maxplayers: "8",
        port: "7777",
        password: "",
        motd: "Welcome to Terraria!",
        worldpath: "./worlds",
        banlist: "banlist.txt",
        secure: "1",
      },
      cpu: 2,
      memory: 2,
      storage: 5,
      enableMods: false,
      mods: [],
      startupCommands: "TerrariaServer.exe -config serverconfig.txt",
      backupEnabled: true,
      backupSchedule: "0 0 * * *",
      autoRestart: false,
      restartSchedule: "0 4 * * *",
    },
  },

  // Rust Templates
  {
    id: "rust-vanilla",
    name: "Rust Vanilla",
    description: "Standard Rust server with default settings",
    gameType: "rust",
    tags: ["survival", "pvp", "vanilla"],
    popular: true,
    config: {
      name: "Rust Vanilla Server",
      gameType: "rust",
      description: "A standard Rust server with default settings",
      version: "latest",
      port: 28015,
      maxPlayers: 100,
      serverProperties: {
        "server.hostname": "Vanilla Rust Server",
        "server.description": "A vanilla Rust server",
        "server.headerimage": "",
        "server.url": "",
        "server.identity": "rust-server",
        "server.seed": "0",
        "server.maxplayers": "100",
        "server.worldsize": "3500",
        "server.saveinterval": "300",
        "server.secure": "true",
        "rcon.port": "28016",
        "rcon.password": "CHANGEME",
        "rcon.web": "1",
      },
      cpu: 8,
      memory: 16,
      storage: 30,
      enableMods: false,
      mods: [],
      startupCommands:
        './RustDedicated -batchmode +server.port 28015 +server.identity "rust-server" +rcon.port 28016 +rcon.password "CHANGEME" +rcon.web 1 +server.maxplayers 100 +server.hostname "Vanilla Rust Server" +server.worldsize 3500 +server.saveinterval 300',
      backupEnabled: true,
      backupSchedule: "0 */6 * * *",
      autoRestart: true,
      restartSchedule: "0 4 * * *",
    },
  },
]
